name: "ESPHome Editor"
description: "EspHome-Editor is a tool designed to streamline the creation and management of YAML configurations for EspHome. If you're working with devices that have many similar components or deploying multiple similar devices, this tool is here to save you time and effort"
version: "0.2.0"
url: https://github.com/Morcatko/EspHome-Editor
slug: "esphome_editor"
panel_title: "ESPHome Editor"
init: false
homeassistant_api: true
hassio_api: true
hassio_role: manager
host_network: true
#apparmor: false
map:
  - type: addon_config
    read_only: false
    path: /app/work-folder/
ingress: true
ingress_port: 3000
image: morcatko/esphome-editor-dev
arch:
  - amd64
